name: libri-light
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - torchvision
  - cudatoolkit
  - torchaudio
  - numpy
  - pysoundfile
  - pip
  - openblas-devel
  - tqdm
  - nose
  - pip:
    - progressbar2
    - matplotlib
    - torchaudio
    - termcolor
